# SPDX-FileCopyrightText: Copyright (c) 2026 torch-cuda sandbox contributors
# SPDX-License-Identifier: Apache-2.0
"""Render committed `.cubin` files into a C header of byte arrays.

Split out from `prepare_cubins.py` because the two run in different places and
for different reasons. Compiling SASS needs a CUDA toolkit and the private
kernel sources, so it happens once in the internal pipeline; embedding only
needs the resulting `.cubin` files, so it happens on every build, including a
public build that has neither.

CMake invokes this; the header lands in the build tree and is never committed.
Nothing here is a source of truth — delete the output and the next build
regenerates it.

    python cpp/tools/embed_cubins.py --cubin-dir cpp/kernels/vector_add/cubins \\
                                     --output build/embedded_cubins.h
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

# `<kernel>.sm<arch>.<dtype>.cubin` — the shape prepare_cubins.py writes.
CUBIN_NAME = re.compile(r"^(?P<kernel>.+)\.sm(?P<sm>\d+)\.(?P<dtype>[a-z0-9]+)\.cubin$")


@dataclass(frozen=True)
class Image:
    """One compiled kernel image found on disk."""

    kernel: str
    sm: int
    dtype: str
    path: Path
    entry: str

    @property
    def symbol(self) -> str:
        return f"k_{self.kernel}_sm{self.sm}_{self.dtype}"


def entry_symbol(cubin: Path) -> str:
    """Read the kernel's real CUDA symbol out of the CUBIN.

    The name `cuModuleGetFunction` needs is not the name we call the kernel: the
    DSL mangles it with the traced argument types, e.g.
    `kernel_cutlass_vector_add_kernel_tensorptrf32gmemalign16o1_..._0`. Guessing
    it produces "named symbol not found" at launch, long after the build looked
    fine, so it is read from the artifact and baked into the generated table.

    A CUBIN is an ELF; each kernel gets its own `.text.<symbol>` section, so the
    section header string table is enough — no symbol table walk needed.
    """
    blob = cubin.read_bytes()
    if blob[:4] != b"\x7fELF":
        raise ValueError(f"{cubin} is not an ELF; is it an unfetched LFS pointer?")

    little = "little"
    shoff = int.from_bytes(blob[0x28:0x30], little)
    shentsize = int.from_bytes(blob[0x3A:0x3C], little)
    shnum = int.from_bytes(blob[0x3C:0x3E], little)
    shstrndx = int.from_bytes(blob[0x3E:0x40], little)

    strtab_header = shoff + shstrndx * shentsize
    strtab_off = int.from_bytes(blob[strtab_header + 0x18 : strtab_header + 0x20], little)

    names = []
    for index in range(shnum):
        header = shoff + index * shentsize
        name_off = strtab_off + int.from_bytes(blob[header : header + 4], little)
        end = blob.index(b"\0", name_off)
        name = blob[name_off:end].decode()
        if name.startswith(".text."):
            names.append(name.removeprefix(".text."))

    if len(names) != 1:
        raise ValueError(f"{cubin}: expected exactly one .text.<symbol> section, found {names}")
    return names[0]


def discover(cubin_dir: Path) -> list[Image]:
    """Return every parseable image, in a stable order.

    A file that does not match the naming convention is ignored rather than
    fatal: the directory is also where a debug dump or a stray download lands,
    and failing the build over one would be hostile.
    """
    images = []
    for path in sorted(cubin_dir.glob("*.cubin")):
        match = CUBIN_NAME.match(path.name)
        if match is None:
            continue
        images.append(
            Image(
                kernel=match["kernel"],
                sm=int(match["sm"]),
                dtype=match["dtype"],
                path=path,
                entry=entry_symbol(path),
            )
        )
    return images


def render(images: list[Image]) -> str:
    lines = [
        "// Generated by cpp/tools/embed_cubins.py. DO NOT EDIT, DO NOT COMMIT.",
        "#pragma once",
        "",
        '#include "cubin_runtime.h"',
        "",
        "#include <cstddef>",
        "#include <string>",
        "",
        "namespace torch_cuda {",
        "",
    ]

    for image in images:
        payload = image.path.read_bytes()
        body = ",".join(str(byte) for byte in payload)
        lines += [
            f"// {image.kernel} @ sm_{image.sm} {image.dtype} ({len(payload)} bytes), entry {image.entry}",
            f"inline constexpr unsigned char {image.symbol}[] = {{{body}}};",
            "",
        ]

    lines += ["inline const CubinImage* find_embedded_cubin(const std::string& name, int sm_arch)", "{"]
    if not images:
        # No images is a legitimate state: a checkout without LFS objects, or a
        # tree whose kernels have not been built yet. Returning nullptr sends the
        # Python layer down its fallback chain instead of failing the build.
        lines += ["  (void) name;", "  (void) sm_arch;"]
    for image in images:
        lines += [
            f'  if (name == "{image.kernel}" && sm_arch == {image.sm})',
            "  {",
            f'    static constexpr CubinImage image{{{image.sm}, "{image.entry}", {image.symbol}, sizeof({image.symbol})}};',
            "    return &image;",
            "  }",
        ]
    lines += ["  return nullptr;", "}", "", "} // namespace torch_cuda", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cubin-dir", type=Path, required=True, help="directory holding the committed .cubin files")
    parser.add_argument("--output", type=Path, required=True, help="header to write, inside the build tree")
    args = parser.parse_args()

    images = discover(args.cubin_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)

    rendered = render(images)
    # Only rewrite on change, so CMake does not rebuild every dependent object
    # when nothing about the images actually moved.
    if args.output.exists() and args.output.read_text() == rendered:
        print(f"{args.output}: unchanged ({len(images)} images)")
        return 0

    args.output.write_text(rendered)
    total = sum(image.path.stat().st_size for image in images)
    print(f"{args.output}: {len(images)} images, {total} bytes of SASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
